<a href="https://colab.research.google.com/github/Kalyan-kumar2000/DAP/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as npa 
npa= npa.array([1, 2, 3])
print(npa)

[1 2 3]


In [ ]:
import numpy as npp
a = npp.array([[1 , 2, 3, 4],[5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
a=np.ones(2)
print(a)

[1. 1.]


In [ ]:
import numpy as np
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
y = np.ones(5, dtype=float)
print(y)
y

[1. 1. 1. 1. 1.]


array([1., 1., 1., 1., 1.])

In [ ]:
import numpy as np
a=np.arange(2,9,3)
print(a)

[2 5 8]


In [ ]:
import numpy as np
a=np.ones(4)
print(a)

[1. 1. 1. 1.]


In [ ]:
arr = np.array([2,4,3,2,4,4,3])
print(arr)

[2 4 3 2 4 4 3]


In [ ]:
a = np.array([3,5,2,8,2,4,])
print(a)


a=np.delete(a, 1)
print(a)

[3 5 2 8 2 4]
[3 2 8 2 4]


In [ ]:
a = np.array([2,55,3,6,22,578,22345])
print(a)


a=np.sort(a)
print(a)

[    2    55     3     6    22   578 22345]
[    2     3     6    22    55   578 22345]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
a=arr.ndim
print(arr) 
print("dimensions = ", a)

[[1 2 3]
 [4 5 6]]
dimensions =  2


In [ ]:
import numpy as np

a = np.array(999)
b = np.array([4,3,5,2,])
c = np.array([[5,2,7], [5,3,5,]])
d = np.array([[[1, 2, 2], [5,7,4,]], [[1, 1, 3], [3,3,3]]])

print(a)
print("dimension= ", a.ndim)
print(b)
print("dimension= ", b.ndim)
print(c)
print("dimension= ", c.ndim)
print(d)
print("dimension= ", d.ndim)

999
dimension=  0
[4 3 5 2]
dimension=  1
[[5 2 7]
 [5 3 5]]
dimension=  2
[[[1 2 2]
  [5 7 4]]

 [[1 1 3]
  [3 3 3]]]
dimension=  3


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [5, 6, 7]])

print(arr.shape) 

(2, 3)
